version: "3.9"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 kaxoot.asgi:application
    volumes:
      - .:/app
    ports:
      - "5000:8000"
    depends_on:
      - db
      - redis
    networks:
      static-network:
        ipv4_address: 172.20.0.6

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      static-network:
        ipv4_address: 172.20.0.8
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24