# Generated by Django 5.2.5 on 2025-09-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='ball',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='start_time',
        ),
    ]
