# Generated by Django 5.2.5 on 2025-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_ball_level_point_remove_questions_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
