# Generated by Django 5.2.5 on 2025-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_questions_level_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='group',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
