# Generated by Django 5.2.5 on 2025-09-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_useranswers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.group'),
        ),
    ]
