# Generated by Django 5.2.5 on 2025-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_useranswers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
