# Generated by Django 5.2.5 on 2025-08-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_result_rank_delete_rankgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pin',
        ),
    ]
