# Generated by Django 5.2.5 on 2025-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_group_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
