# Generated by Django 5.2.5 on 2025-08-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_group_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
